subfields = {
    'physics': {"subjects": ["basic mechanics", "basic electromagnetism", "basic lens magnification effects", "waves", "kinematics",
                "basic thermodynamics", "heat diffusion in 1D", "cosmology", "refraction through 1-3 different materials",
                "reflections", "bouncing ball height after 1-3 bounces", "change in kinetic energy",
                "basic projectile motion (no trig)", "basic doppler effect shifts", "basic fluid dynamics", "change in mass",
                "gravity effects", "water level change from faucet", 
                "work-energy principle (no integration)", "uniform circular motion", "elastic collisions",
                "inelastic collisions", "simple harmonic motion", "basic resonance in strings/pipes", "wave interference",
                "sound intensity vs distance", "simple ohm's law applications", "simple charging/discharging capacitors",
                "basic magnetic forces on a moving charge", "basic phase change calculations", "basic buoyancy",
                "basic orbital periods", "basic escape velocity", "center of mass of simple systems", "basic polarization"],
                "concepts": ["position updates over time", "simple force-based movement", "energy transfer",
                             "light reflection", "temperature changes", "charge buildup", "friction forces",
                             "elastic object collisions", "inelastic object collisions", "object collisions",
                             "velocity estimation", "time estimation", "gravitational attraction",
                             "net force from multiple sources", "orbit approximations without calculus"],
                "q_types": [],
                "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios."},
    'chemistry': [],
    'biology': [],
    'earth-science': [],
    'computer-science': [],
    'math': [],
    'logic-and-reasoning': [],
    'linguistics': [],
    'geography': [],
    'medicine-anatomy': [],
    'adv-physics': {"subjects": ["special relativity", "general relativity", "time delay due to signal travel",
                    "particle in a box energy levels", "photoelectric effect thresholds",
                    "energy transitions in atoms", "heisenberg uncertainty principle", "half spin system probabilities",
                    "wavefunctional normalization checks", "time dilation", "length contraction scenarios",
                    "relativistic momentum and energy", "gravitational redshift (simplified)",
                    "escape from a Schwarzschild radius", "partition functions for 2-3 energy levels",
                    "Boltzmann distribution probabilities", "entropy change in simple mixing problems",
                    "Carnot efficiency limits", "mean free path in gases", "magnetic flux and induced EMF (Faraday's law)",
                    "LC circuit oscillations", "radiation pressure on a surface", "dipole electric field at a point",
                    "lagrangian of a simple system", "coupled oscillators", "normal mode frequencies",
                    "rotational kinetic energy of rigid bodies", "non-inertial frames (fictitious forces)",
                    "Hubble's law distance/velocity problems", "stellar luminosity from Stefan-Boltzmann law",
                    "Chandrasekhar limit estimates", "blackbody spectrum peak wavelength (Wien's law)",
                    "critical density of the universe (flat vs open)", "binding energy", "decay chain half-life calculations",
                    "simple cross-section probability estimates", "quark composition", "charge conservation in nuclear reactions"],
                    "q_types": [],
                    "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra."
                    },
    'adv-chemistry': [],
    'adv-biology': [],
    'adv-earth science': [],
    'adv-computer science': [],
    'adv-math': [],
}

interactions = {
    'general_concepts': [],
    'general_qtypes': ["checking conditions on each element", "filtering a collection based on rules",
                       "transforming each element in a collection", "accumulating a result cross a loop",
                       "validating properties of an input", "reordering or sorting values", "reformatting a string or number"
                       "traversing nested structures", "searching for a target match", "extracting or slicing part of a value",
                       "converting between representations", "removing or replacing parts of data",
                       "tracking a running total or count", "checking for uniqueness or duplicates",
                       "counting specific patterns or types", "computing a simple numeric property"],
}