
subject_mappings = {'physics': 'physics',
                    'chemistry': 'chemistry',
                    'biology': 'biology',
                    'earth-science': 'earth science',
                    'computer-science': 'computer science',
                    'math': 'math',
                    'logic-and-reasoning': 'logic and reasoning',
                    'linguistics': 'linguistics',
                    'geography': 'geography',
                    'medicine-anatomy': 'medicine/anatomy',
                    'adv-physics': 'physics',
                    'adv-chemistry': 'chemistry',
                    'adv-biology': 'biology',
                    'adv-earth-science': 'earth science',
                    'adv-computer-science': 'computer science',
                    'adv-math': 'math'}

structure_mappings = {"enumerate": "enumerate()",
                      "zip": "zip()",
                      "any/all": "any()/all()",
                      "map/filter": "map()/filter()",
                      "set-operations": "set operations",
                      "data-slicing": "data slicing",
                      "conditional-chaining": "conditional chaining",
                      "comprehensions": "comprehensions",
                      "lambda-functions": "lambda functions",
                      "args-and-kwargs": "args and kwargs",
                      "nested for loops": "nested for loops",
                      "for loops": "for loops",
                      "while loops": "while loops",
                     }

instructions = {"base_query": "I\'d like you to generate a snippet of Python code for me. The purpose of the code is educational and should help students practice reading code.",
                "code_mode_output": {"do": ["Use i, j, and k for iterators in \"for\" loops.",
                                            "Store the output of the code in a variable called \"output\", where the last line prints the output variable.",
                                            "The number of iterations through the most nested for loop should never be more than 5 (if using for loops).",
                                            "The output should be limited to 10 characters or fewer, and not more than one line long. The output must be something the user can type into a text box (not contain weird characters or symbols).",
                                            "The output of the code must be easy to determine with mental math."
                                            ],
                                     "do-not": ["Do not include descriptions of the code.",
                                                "Do not use input() or random() functions in the code.",
                                                "Do not include descriptions of, or introductions to, the code. Just respond with the code.",
                                                "Do not include comments, annotations, or docstrings in the code."
                                                ],
                },
                "code_mode_completion": {"do": ["Use i, j, and k for iterators in for loops.",
                                                "The code should have docstrings following the PEP8 Python styling conventions. Write one docstring for each function and class that contains a short summary, descriptions of parameters, and the function return value (if applicable). Use \"Args\" and \"Returns\" for this.",
                                                "All code must be wrapped in a function or a class."
                                                ],
                                         "do-not": ["Do not write any annotations for the code.",
                                                    "Do not include descriptions of, or introductions to, the code. Just respond with the code.",
                                                    "Do not write docstrings for __init__() functions.",
                                                    ],
                },
                "determine_output": {"do": [#"Use i, j, and k for iterators in \"for\" loops.",
                                            "Store the output of the code in a variable called \"output\", where the last line prints the output variable.",
                                            "The number of iterations through the most nested for loop should never be more than 5 (if using for loops).",
                                            "The output should be limited to 10 characters or fewer, and not more than one line long. The output must be something the user can type into a text box (not contain weird characters or symbols).",
                                            "The output of the code must be easy to determine with mental math."
                                            ],
                                     "do-not": ["Do not use input() or random() functions in the code.",
                                                "Do not include descriptions of, or introductions to, the code. Just respond with the code.",
                                                "Do not include comments, annotations, or docstrings in the code.",
                                                "Do not use any functions. Focus on a few lines that are difficult to interpret, but require little to no mental math. If the subject and domain is complex, use a few lines that you might see in such a program. E.x: if the subject is 'quantum mechanics', preference short code over code that is meaningful and accurate to quantum mechanics.",
                                                "Do not use any complicated equations. Focus on the conceptual pieces and the 'spirit' of the subject and domain.",
                                                "The answer cannot be null, or an empty string.",
                                                ],
                },
                "fill_in_vars": {"do": ["Use i, j, and k for iterators in for loops.",
                                        "The code should have docstrings following the PEP8 Python styling conventions. Write one docstring for each function and class that contains a short summary, descriptions of parameters, and the function return value (if applicable). Use \"Args\" and \"Returns\" for this.",
                                        "All code must be wrapped in a function or a class."
                                        ],
                                 "do-not": ["Do not write any annotations for the code.",
                                            "Do not include descriptions of, or introductions to, the code. Just respond with the code.",
                                             "Do not write docstrings for __init__() functions.",
                                           ],
                },
                "drag_and_drop": {"do": ["Use i, j, and k for iterators in \"for\" loops.",
                                         "Store the output of the code in a variable called \"output\", where the last line prints the output variable.",
                                         "The number of iterations through the most nested for loop should never be more than 5 (if using for loops).",
                                         "The output should be limited to 10 characters or fewer, and not more than one line long. The output must be something the user can type into a text box (not contain weird characters or symbols).",
                                         "The output of the code must be easy to determine with mental math."
                                         "Most code should be wrapped in functions, but that \"output\" variable must be outside functions and still print something at the end."
                                        ],
                                  "do-not": ["Do not include descriptions of the code.",
                                             "Do not use input() or random() functions in the code.",
                                             "Do not include descriptions of, or introductions to, the code. Just respond with the code.",
                                             "Do not include comments, annotations, or docstrings in the code."
                                            ],
                },

                
}

subfield_info = {
    'physics': {"subjects": ["basic mechanics",
                             "basic electromagnetism",
                             "basic lens magnification effects",
                             "waves",
                             "kinematics",
                             "basic thermodynamics",
                             "heat diffusion in 1D",
                             "basic astronomy",
                             "refraction through 1-3 different materials",
                             "reflections",
                             "bouncing ball height after 1-3 bounces",
                             "change in kinetic energy",
                             "basic projectile motion (no trig)",
                             "basic doppler effect shifts",
                             "basic fluid dynamics",
                             "change in mass",
                             "gravity effects",
                             "water level change from faucet",
                             "work-energy principle (no integration)",
                             "uniform circular motion",
                             "elastic collisions",
                             "inelastic collisions",
                             "simple harmonic motion",
                             "basic resonance in strings/pipes",
                             "wave interference",
                             "sound intensity vs distance",
                             "simple ohm's law applications",
                             "simple charging/discharging capacitors",
                             "basic magnetic forces on a moving charge",
                             "basic phase change calculations",
                             "basic buoyancy",
                             "basic orbital periods",
                             "basic escape velocity",
                             "center of mass of simple systems",
                             "basic polarization"],
                "concepts": ["position updates over time",
                             "simple force-based movement",
                             "energy transfer",
                             "light reflection",
                             "temperature changes",
                             "charge buildup",
                             "friction forces",
                             "elastic object collisions",
                             "inelastic object collisions",
                             "object collisions",
                             "velocity estimation",
                             "time estimation",
                             "gravitational attraction",
                             "net force from multiple sources",
                             "orbit approximations without calculus"],
                "q_types": ["estimating magnitude of change from initial conditions",
                            "comparing theoretical predictions with observed outcomes",
                            "modeling interaction strength between two entities",
                            "estimating energy or resource consumption",
                            "determining stability under varying conditions",
                            "simulating feedback effects within a system",
                            "computing probability of an event occurring",
                            "balancing quantities between two or more systems",
                            "tracking changes in a variable over discrete time steps",
                            "converting between measurement units",
                            "identifying a limiting factor in a process",
                            "calculating efficiency or percent yield",
                            "modeling growth or decay using exponential relationships",
                            "predicting system behavior under changing conditions"],
                "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios."
                },
    'chemistry': {"subjects": ["stoichiometry",
                               "simple Lewis structures",
                               "simple electron configurations",
                               "valence electrons & the octet rule",
                               "ionic vs covalent bonding",
                               "polar vs nonpolar molecules",
                               "basic VSEPR shapes",
                               "simple intermolecular forces",
                               "naming simple compounds",
                               "simple balancing chemical equations",
                               "simple gas laws (Boyle's, Charles's, combined, ideal gas)",
                               "changes of state",
                               "density and concentration",
                               "properties of acids",
                               "properties of bases",
                               "pH and pOH calculations with simple numbers",
                               "dilution calculations",
                               "identifying acids, bases, and salts",
                               "exothermic vs endothermic reactions",
                               "simple calorimetry",
                               "heat transfer and conservation of energy",
                               "law of conservation of mass in reactions",
                               "types of radiation (basic recognition of alpha, beta, or gamma)",
                               "half life problems with whole-number steps",
                               "identifying isotopes",
                               "basic fission vs fusion (conceptual)"],
                   "concepts": ["balancing elements across reactions and products",
                                "simulating concentration changes over time",
                                "converting grams to moles or vice versa",
                                "identifying limiting reagents",
                                "calculating percent yield",
                                "simulating ph changes in titrations",
                                "tracking energy released",
                                "tracking energy absorbed",
                                "determining reaction rate based on time steps",
                                "simulating half-life decay",
                                "modeling temperature and pressure effects on volume",
                                "assigning electron configurations",
                                "sorting elements by some attribute (atomic radius, etc.)",
                                "predicting solubility using polarity",
                                "modeling phase transitions",
                                "simulating catalyse effects based on yield",
                                "estimating number of ions dissolved in solution"],
                   "q_types": ["estimating magnitude of change from initial conditions",
                                "comparing theoretical predictions with observed outcomes",
                                "modeling interaction strength between two entities",
                                "estimating energy or resource consumption",
                                "determining stability under varying conditions",
                                "simulating feedback effects within a system",
                                "computing probability of an event occurring",
                                "balancing quantities between two or more systems",
                                "tracking changes in a variable over discrete time steps",
                                "converting between measurement units",
                                "identifying a limiting factor in a process",
                                "calculating efficiency or percent yield",
                                "modeling growth or decay using exponential relationships",
                                "predicting system behavior under changing conditions"],
                   "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios."
                   },
    'biology': {"subjects": ["cell structure and function",
                             "dna structure and replication basics",
                             "transcription and translation",
                             "basic genetics",
                             "enzyme activity and factors affecting rate",
                             "photosynthesis and cellular respiration",
                             "human body systems basics",
                             "ecology fundamentals",
                             "microorganisms and simple immune responses",
                             "evolution and natural selection concepts",
                             "population growth and regulation",
                             "basic anatomy terms and functions",
                             "plant structure and function",
                             "cell division basics",
                             "simple behavior and stimulus-response mechanisms"],
                 "concepts": ["identifying cell structures",
                              "tracking growth stages",
                              "classifying organisms",
                              "analyzing genetic traits",
                              "modeling photosynthesis process",
                              "simulating respiration",
                              "measuring enzyme activity",
                              "monitoring population changes",
                              "tracking nutrient cycles",
                              "analyzing DNA sequences",
                              "studying organism behavior",
                              "classifying tissues",
                              "measuring metabolic rates",
                              "observing cell division",
                              "mapping food chains",
                              "analyzing habitats",
                              "tracking environmental impacts",
                              "monitoring immune responses",
                              "studying reproduction methods",
                              "measuring biodiversity"],
                 "q_types": ["identifying cell organelles",
                             "classifying species",
                             "predicting genetic inheritance",
                             "explaining metabolic pathways",
                             "calculating growth rates",
                             "determining enzyme effects",
                             "tracing nutrient flow",
                             "analyzing population trends",
                             "describing reproductive cycles",
                             "mapping food web interactions",
                             "interpreting DNA patterns",
                             "classifying tissue types",
                             "explaining respiration stages",
                             "predicting organism behavior",
                             "measuring biodiversity indices",
                             "describing immune system functions",
                             "analyzing environmental adaptations",
                             "identifying stages of mitosis",
                             "explaining photosynthesis steps",
                             "assessing habitat changes"],
                 "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
               },
    'earth-science': {"subjects": ["geology and rock classification",
                                   "plate tectonics and fault mechanics",
                                   "volcanology and eruption types",
                                   "seismology and earthquake measurement",
                                   "soil composition and formation",
                                   "weather patterns and atmospheric dynamics",
                                   "climate change and environmental impact",
                                   "hydrology and water cycle processes",
                                   "oceanography and marine ecosystems",
                                   "mineralogy and crystal structures",
                                   "glaciology and ice dynamics",
                                   "natural resource management",
                                   "geomorphology and landform development",
                                   "atmospheric chemistry and pollution",
                                   "paleontology and fossil records",
                                   "simple plate tectonics",
                                   "simple seismology",
                                   "simple volcanology",
                                   "simple ocean currents",
                                   "simple weather patterns",
                                   "simple climate change",
                                   "simple layers of the earth",
                                   "simple rock cycles",
                                   "simple soil formation",
                                   "simple erosion and deposition",
                                   "simple earth's magnetic field",
                                   "simple greenhouse gases",
                                   "simple atmospheric pressure",
                                   "simple cloud formation",
                                   "simple water cycle",
                                   "simple solar radiation",
                                   "simple seasons"],
                      "concepts": ["analyzing rock and soil composition",
                                   "tracking erosion or deposition over time",
                                   "modeling water cycle components",
                                   "simulating weather pattern changes",
                                   "measuring mineral hardness or density",
                                   "calculating sediment transport",
                                   "identifying landform types",
                                   "interpreting seismic wave data",
                                   "estimating age using radiometric dating",
                                   "mapping tectonic plate boundaries",
                                   "tracking changes in natural resource levels",
                                   "calculating energy flow in ecosystems",
                                   "classifying soil types",
                                   "measuring water quality parameters",
                                   "simulating volcanic activity",
                                   "modeling atmospheric pressure variations",
                                   "tracking glacier advance and retreat",
                                   "predicting flood likelihood",
                                   "calculating slope stability",
                                   "analyzing fossil distribution patterns"],
                      "q_types": ["tracking a gradual change in a physical property"
                                   "simulating an environmental process over several steps"
                                   "updating a value based on its interactions with its neighbors"
                                   "computing how a variable changes over time or space"
                                   "checking if conditions match a known pattern"
                                   "identifying significant points in a range"
                                   "flagging outliers or abnormal readings"],
                      "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
                     },
    'computer-science': {"subjects": ["basic data structures",
                                      "control flow and decision making",
                                      "arrays and list structures",
                                      "stacks and queues basics",
                                      "hash tables introduction",
                                      "string searching and matching",
                                      "pattern recognition with strings",
                                      "boolean algebra fundamentals",
                                      "set theory in computing",
                                      "basic number systems (binary, octal, hex)",
                                      "logic gates and truth tables",
                                      "digital circuits overview",
                                      "computer architecture fundamentals",
                                      "memory hierarchy basics",
                                      "operating system fundamentals",
                                      "file system organization (conceptual)",
                                      "process scheduling basics",
                                      "basic networking concepts",
                                      "IP addressing and subnets overview",
                                      "client-server model introduction",
                                      "cybersecurity fundamentals",
                                      "cryptography basics (ciphers, keys)",
                                      "software engineering life cycle",
                                      "testing and debugging fundamentals",
                                      "version control basics",
                                      "object-oriented programming concepts",
                                      "class design and instantiation",
                                      "inheritance and polymorphism basics",
                                      "modularity and code reuse",
                                      "functional programming introduction",
                                      "event-driven programming basics",
                                      "graphical user interface basics",
                                      "database fundamentals",
                                      "relational databases and SQL basics",
                                      "entity-relationship modeling",
                                      "data normalization basics",
                                      "web development fundamentals",
                                      "HTML and CSS basics",
                                      "JavaScript fundamentals",
                                      "client-server communication basics",
                                      "cloud computing fundamentals",
                                      "parallelism and concurrency basics",
                                      "big-O notation and time complexity",
                                      "data structures",
                                      "sorting data",
                                      "searching through data",
                                      "string manipulation",
                                      "recursion",
                                      "basic algorithms",
                                      "memory simulation",
                                      "bitwise operations",
                                      "encoding",
                                      "decoding",
                                      "simulation of logic gates",
                                      "graph traversal (non-heavy, simple DFS/BFS)",
                                      "binary trees",
                                      "heaps",
                                      "hashing",
                                      "collisions",
                                      "finite state machines",
                                      "basic compilers",
                                      "basic interpreters",
                                      "virtual machines (simplified)",
                                      "cpu scheduling",
                                      "stack simulation",
                                      "queue simulation",
                                      "instruction sets",
                                      "memory layout",
                                      "rest api design basics",
                                      "request handling and routing",
                                      "json data parsing",
                                      "user authentication logic",
                                      "session/token simulation",
                                      "form submission processing",
                                      "crud operations (create, read, update, delete)",
                                      "input validation and sanitization",
                                      "pagination and search filtering",
                                      "error logging and handling",
                                      "configuration loading (e.g. from json and env dicts)",
                                      "rate limiting simulation",
                                      "basic job queue simulation",
                                      "email/message formatting",
                                      "file upload simulation",
                                      "time-based job simulation (e.g. cron-like behavior)",
                                      "simple database query emulation (no sql)",
                                      "microservice communication (mocked with dicts/function)",
                                      "simulated cloud storage or blob access",
                                      "basic analytics pipeline (e.g. log -> stats)",
                                      "api design",
                                      "frontend-backend communication",
                                      "database querying",
                                      "data serialization",
                                      "devops and deployment",
                                      "networking",
                                      "rate limiting",
                                      "code linting and formatting",
                                      "cloud storage interactions",
                                      "package management"],
                         "concepts": ["simulating execution over multiple steps",
                                      "updating states",
                                      "tracking resource usage over time",
                                      "checking consistency of a system",
                                      "validating a system",
                                      "counting the number of operations of a system",
                                      "comparing two outputs for correctness",
                                      "evaluating logic conditions",
                                      "classifying inputs",
                                      "checking if a pattern exists in another",
                                      "finding the most used memory/register/element",
                                      "summarizing the final state of a system",
                                      "tracking growth of a structure",
                                      "measuring depth, size, or height of a system",
                                      "flagging special or end cases",
                                      "computing differences between two configurations",
                                      "identifying when a system reaches a halting condition",
                                      "determining whether a structure satisfies constraints",
                                      "extracing fields from json/dictionaries",
                                      "transforming or formatting structured data",
                                      "merging or splitting structured inputs",
                                      "handling missing or malformed data",
                                      "simulating login/logout flow",
                                      "checking if session/token is vlid",
                                      "validating user inputs against criteria (without using input())",
                                      "counting user interactions",
                                      "returning appropriate http-like codes based on input",
                                      "simulating an api request and response cycle",
                                      "checking if input follows schema (without using input())",
                                      "verifying if request contains required fields",
                                      "simulating api unit test behavior",
                                      "resolving data conflicts"],
                         "q_types": ["formatting structured data",
                                     "identifying missing fields",
                                     "simulating an api response",
                                     "filtering logs or entries",
                                     "retrying failed operations",
                                     "handling state transitions",
                                     "processing a batch of inputs (without input())",
                                     "simulating a cache hit or miss",
                                     "validating constraints",
                                     "checking configuration values",
                                     "parsing a data structure",
                                     "generating example output",
                                     "detecting common user errors",
                                     "simulating user authentication flow",
                                     "tracking session validity",
                                     "counting occurrences in data",
                                     "handling error codes and messages",
                                     "simulating database query results",
                                     "validating json schema structure",
                                     "logging system events"],
                         "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
                        },
    'math': {"subjects": ["arithmetic operations",
                          "order of operations",
                          "fractions and decimals",
                          "percentages",
                          "ratios and proportions",
                          "negative numbers",
                          "factors and multiples",
                          "prime numbers and composites",
                          "greatest common divisor",
                          "least common multiple",
                          "basic exponents",
                          "square roots and radicals",
                          "simple equations",
                          "inequalities",
                          "basic algebraic expressions",
                          "coordinate plane basics",
                          "slopes of lines",
                          "simple linear equations",
                          "basic geometry shapes",
                          "perimeter and area",
                          "volume of simple solids",
                          "angles and triangles",
                          "circles and circumference",
                          "probability basics",
                          "combinations and permutations basics",
                          "mean, median, mode",
                          "basic data interpretation",
                          "patterns and sequences",
                          "basic modular arithmetic"],
             "concepts": ["performing basic arithmetic operations",
                          "applying order of operations",
                          "converting between fractions and decimals",
                          "calculating percentages",
                          "comparing ratios or proportions",
                          "working with negative numbers",
                          "finding factors of a number",
                          "identifying prime numbers",
                          "computing greatest common divisor",
                          "computing least common multiple",
                          "evaluating simple exponents",
                          "calculating square roots",
                          "solving simple linear equations",
                          "graphing points on a coordinate plane",
                          "determining the slope of a line",
                          "finding the perimeter of basic shapes",
                          "calculating the area of simple shapes",
                          "computing the volume of solids",
                          "measuring angles",
                          "classifying triangles by sides and angles",
                          "calculating circumference of a circle",
                          "determining probability of simple events",
                          "counting possible outcomes",
                          "finding mean, median, and mode",
                          "interpreting data from charts or tables",
                          "recognizing number patterns",
                          "continuing arithmetic sequences"],
             "q_types": ["performing basic arithmetic",
                         "applying order of operations",
                         "converting between fractions and decimals",
                         "calculating percentages",
                         "comparing ratios or proportions",
                         "working with negative numbers",
                         "finding factors of a number",
                         "identifying prime numbers",
                         "computing greatest common divisor",
                         "computing least common multiple",
                         "evaluating simple exponents",
                         "calculating square roots",
                         "solving simple linear equations",
                         "graphing points on a coordinate plane",
                         "determining the slope of a line",
                         "solving for an unknown variable",
                         "finding the perimeter of a shape",
                         "calculating the area of basic shapes",
                         "computing the volume of simple solids",
                         "measuring or estimating angles",
                         "classifying types of triangles",
                         "computing circumference of a circle",
                         "determining probability of simple events",
                         "counting possible outcomes",
                         "finding mean, median, and mode",
                         "interpreting data from a chart",
                         "recognizing number patterns",
                         "continuing arithmetic sequences",
                         "applying basic modular arithmetic",
                         "checking numerical conditions",
                         "counting values with a property",
                         "tracking running totals or sequences",
                         "computing a transformation",
                         "detecting a classification",
                         "generating structured input",
                         "looping through a mathematical range",
                         "pattern detection or repetition",
                         "building up from a recurrence",
                         "checking equivalence across representations",
                         "grouping or filtering by criteria"],
             "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
            },
    'logic-and-reasoning': {"subjects": ["propositional logic",
                                         "predicate logic",
                                         "boolean algebra",
                                         "logical puzzles",
                                         "truth tables",
                                         "logical circuits",
                                         "set theory",
                                         "proof techniques",
                                         "syllogisms",
                                         "logical fallacies",
                                         "deductive reasoning",
                                         "inductive reasoning",
                                         "paradoxes",
                                         "decision making",
                                         "problem solving strategies",
                                         "logical inference",
                                         "constraint satisfaction problems",
                                         "symbolic logic",
                                         "modal logic",
                                         "fuzzy logic"],
                            "concepts": ["evaluating truth values",
                                         "simplifying logical expressions",
                                         "identifying valid and invalid arguments",
                                         "detecting contradictions",
                                         "translating verbal statements into logic",
                                         "solving puzzles with constraints",
                                         "reasoning with quantifiers",
                                         "analyzing logical fallacies",
                                         "building logical circuits",
                                         "deducing conclusions from premises",
                                         "classifying types of syllogisms",
                                         "mapping logical equivalences",
                                         "applying modus ponens and modus tollens",
                                         "evaluating conditional statements",
                                         "working with set operations and relations",
                                         "handling uncertainty in reasoning",
                                         "modeling decision trees"],
                            "q_types": ["evaluating the truth of a statement",
                                        "completing a truth table",
                                        "simplifying a logical expression",
                                        "identifying logical errors in reasoning",
                                        "determining the validity of an argument",
                                        "constructing a formal proof",
                                        "translating a statement into logical form",
                                        "solving a constraint-based puzzle",
                                        "finding counterexamples",
                                        "applying logical equivalences",
                                        "completing a Venn diagram",
                                        "designing a logical circuit",
                                        "analyzing syllogistic arguments",
                                        "classifying types of reasoning",
                                        "mapping premises to conclusions",
                                        "evaluating nested conditionals",
                                        "selecting correct logical operators",
                                        "resolving ambiguous statements",
                                        "modeling decision processes",
                                        "debugging logical formulas"],
                            "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
                           },
    'linguistics': {"subjects": ["phonetics",
                                 "phonology",
                                 "morphology",
                                 "syntax",
                                 "semantics",
                                 "pragmatics",
                                 "sociolinguistics",
                                 "psycholinguistics",
                                 "historical linguistics",
                                 "computational linguistics",
                                 "language acquisition",
                                 "discourse analysis",
                                 "lexicography",
                                 "syntax trees",
                                 "language typology",
                                 "speech recognition",
                                 "natural language processing",
                                 "corpus linguistics",
                                 "phonotactics",
                                 "prosody"],
                    "concepts": ["identifying phonemes",
                                 "analyzing syllable structure",
                                 "parsing sentence syntax",
                                 "interpreting semantic roles",
                                 "recognizing morphological patterns",
                                 "constructing syntax trees",
                                 "analyzing speech sounds",
                                 "classifying word classes",
                                 "resolving ambiguity in sentences",
                                 "studying language change over time",
                                 "analyzing discourse coherence",
                                 "detecting pragmatic meaning",
                                 "modeling language acquisition stages",
                                 "processing natural language input",
                                 "building simple parsers",
                                 "tagging parts of speech",
                                 "measuring phonetic features",
                                 "analyzing dialectal variation",
                                 "computing edit distances",
                                 "generating phonological rules"],
                    "q_types": ["identifying phonemes in words",
                                "parsing sentence structure",
                                "labeling parts of speech",
                                "constructing syntax trees",
                                "analyzing semantic relationships",
                                "disambiguating word meanings",
                                "classifying morphological forms",
                                "transcribing speech sounds",
                                "detecting pragmatic implications",
                                "explaining language evolution",
                                "analyzing conversational turns",
                                "recognizing dialect features",
                                "tagging text corpora",
                                "building simple language models",
                                "measuring phonetic differences",
                                "resolving syntactic ambiguities",
                                "predicting morphological derivations",
                                "computing edit distance between words",
                                "applying phonological transformations",
                                "evaluating speech recognition output"],
                    "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
                    },
    'geography': {"subjects": ["physical geography",
                              "human geography",
                              "cartography",
                              "geospatial analysis",
                              "climatology",
                              "geomorphology",
                              "hydrology",
                              "urban geography",
                              "economic geography",
                              "population geography",
                              "biogeography",
                              "environmental geography",
                              "regional geography",
                              "political geography",
                              "transportation geography",
                              "remote sensing",
                              "soil geography",
                              "cultural geography",
                              "geographic information systems (GIS)",
                              "natural hazards"],
                  "concepts": ["interpreting topographic maps",
                               "analyzing climate patterns",
                               "mapping population density",
                               "studying landform formation",
                               "examining urban sprawl",
                               "assessing natural resource distribution",
                               "tracking migration flows",
                               "analyzing soil composition",
                               "evaluating environmental impact",
                               "measuring river discharge",
                               "mapping transportation networks",
                               "studying tectonic plate movement",
                               "identifying biomes",
                               "analyzing political boundaries",
                               "assessing disaster risk",
                               "using remote sensing data",
                               "processing GIS layers",
                               "modeling erosion processes",
                               "examining cultural landscapes",
                               "analyzing economic development patterns"],
                  "q_types": ["reading and interpreting maps",
                              "analyzing spatial data",
                              "calculating distances using coordinates",
                              "identifying landforms",
                              "predicting weather patterns",
                              "mapping population changes",
                              "assessing environmental effects",
                              "classifying biomes",
                              "evaluating urban growth",
                              "explaining natural hazard impacts",
                              "interpreting satellite imagery",
                              "tracing migration routes",
                              "analyzing soil samples",
                              "identifying political regions",
                              "modeling river flow",
                              "designing transportation routes",
                              "classifying climates",
                              "assessing disaster preparedness",
                              "mapping resource locations",
                              "explaining cultural geography patterns"],
                  "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
                     },
    'medicine-anatomy': {"subjects": ["human skeletal system",
                                      "muscular system",
                                      "circulatory system",
                                      "respiratory system",
                                      "digestive system",
                                      "nervous system",
                                      "endocrine system",
                                      "immune system basics",
                                      "basic human anatomy",
                                      "cell structure",
                                      "basic physiology",
                                      "common diseases and conditions",
                                      "human senses",
                                      "basic medical terminology",
                                      "body systems interaction"],
                      "concepts": ["identifying major bones",
                                   "explaining muscle functions",
                                   "tracking blood flow through the heart",
                                   "understanding breathing mechanics",
                                   "describing digestion process",
                                   "mapping nerve pathways",
                                   "explaining hormone functions",
                                   "recognizing immune responses",
                                   "labeling cell components",
                                   "describing basic physiological processes",
                                   "identifying symptoms of common illnesses",
                                   "understanding sensory organ functions",
                                   "using medical terminology correctly",
                                   "understanding system interactions",
                                   "explaining basic medical procedures"],
                      "q_types": ["labeling anatomical diagrams",
                                  "explaining physiological functions",
                                  "identifying body parts from descriptions",
                                  "tracing flow of blood or air",
                                  "matching symptoms to conditions",
                                  "describing functions of organs",
                                  "interpreting medical terminology",
                                  "explaining disease processes",
                                  "classifying tissue types",
                                  "analyzing basic diagnostic information",
                                  "describing sensory input pathways",
                                  "matching hormones to effects",
                                  "explaining system interactions",
                                  "identifying common medical instruments",
                                  "describing first aid procedures"],
                      "notes": "Please do not use advanced math like calculus, linear algebra, or higher order equations. Stick to algebra and ratios.",
                     },
    'adv-physics': {"subjects": ["special relativity",
                                 "general relativity",
                                 "time delay due to signal travel",
                                 "particle in a box energy levels",
                                 "photoelectric effect thresholds",
                                 "energy transitions in atoms",
                                 "heisenberg uncertainty principle",
                                 "half spin system probabilities",
                                 "wavefunctional normalization checks",
                                 "time dilation",
                                 "length contraction scenarios",
                                 "relativistic momentum and energy",
                                 "gravitational redshift (simplified)",
                                 "escape from a Schwarzschild radius",
                                 "partition functions for 2-3 energy levels",
                                 "Boltzmann distribution probabilities",
                                 "entropy change in simple mixing problems",
                                 "Carnot efficiency limits",
                                 "mean free path in gases",
                                 "magnetic flux and induced EMF (Faraday's law)",
                                 "LC circuit oscillations",
                                 "radiation pressure on a surface",
                                 "dipole electric field at a point",
                                 "lagrangian of a simple system",
                                 "coupled oscillators",
                                 "normal mode frequencies",
                                 "rotational kinetic energy of rigid bodies",
                                 "non-inertial frames (fictitious forces)",
                                 "Hubble's law distance/velocity problems",
                                 "stellar luminosity from Stefan-Boltzmann law",
                                 "Chandrasekhar limit estimates",
                                 "blackbody spectrum peak wavelength (Wien's law)",
                                 "critical density of the universe (flat vs open)",
                                 "binding energy",
                                 "decay chain half-life calculations",
                                 "simple cross-section probability estimates",
                                 "quark composition",
                                 "charge conservation in nuclear reactions",
                                 "mechanics",
                                 "electromagnetism",
                                 "fluid dynamics",
                                 "harmonic motion",
                                 "cosmology"],
                    "concepts": ["position updates over time",
                                 "simple force-based movement",
                                 "energy transfer",
                                 "light reflection",
                                 "temperature changes",
                                 "charge buildup",
                                 "friction forces",
                                 "elastic object collisions",
                                 "inelastic object collisions",
                                 "object collisions",
                                 "velocity estimation",
                                 "time estimation",
                                 "gravitational attraction",
                                 "net force from multiple sources",
                                 "orbit approximations without calculus"],
                    "q_types": ["estimating magnitude of change from initial conditions",
                                "comparing theoretical predictions with observed outcomes",
                                "modeling interaction strength between two entities",
                                "estimating energy or resource consumption",
                                "determining stability under varying conditions",
                                "simulating feedback effects within a system",
                                "computing probability of an event occurring",
                                "balancing quantities between two or more systems",
                                "tracking changes in a variable over discrete time steps",
                                "converting between measurement units",
                                "identifying a limiting factor in a process",
                                "calculating efficiency or percent yield",
                                "modeling growth or decay using exponential relationships",
                                "predicting system behavior under changing conditions"],
                    "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra."
                    },
    'adv-chemistry': {"subjects": ["quantum numbers",
                                   "multi-electron atom approximations",
                                   "spectroscopy basics",
                                   "molecular orbital theory (bond order, paramagnetism)",
                                   "hybridization in complex molecules",
                                   "resonance structures & delocalization",
                                   "crystal field theory",
                                   "lattice energy trends (Born-Haber cycle approximations)",
                                   "Nernst equation applications",
                                   "Gibbs free energy & cell potential relationship",
                                   "electrolytic cell calculations",
                                   "solubility product",
                                   "buffer capacity & Henderson-Hasselbalch equation",
                                   "rate laws for multi-step reactions",
                                   "determining reaction order from data",
                                   "activation energy from Arrhenius plots",
                                   "catalysis mechanisms",
                                   "integrated rate laws",
                                   "entropy and enthalpy contributions",
                                   "phase diagrams analysis",
                                   "colligative properties with van't Hoff factor",
                                   "vapor pressure lowering with non-ideal corrections",
                                   "Clausius-Clapeyron equation",
                                   "functional group reactivity trends",
                                   "basic reaction mechanisms (SN1, SN2, E1, E2)",
                                   "stereochemistry (R/S configuration, cis/trans isomers)",
                                   "amino acid and peptide chemistry",
                                   "enzyme kinetics",
                                   "mass defect and binding energy",
                                   "radioactive decay chains",
                                   "fission vs fusion energy yields",
                                   "radiotracer applications",
                                   "radiation dosage calculations",
                                   "colligative property deviations",
                                   "equilibrium constant relationships (Kp vs Kc)",
                                   "surface chemistry (adsorption isotherms)",
                                   "crystal structures and unit cells",
                                   "computational chemistry basics"],
                      "concepts": ["balancing elements across reactions and products",
                                   "simulating concentration changes over time",
                                   "converting grams to moles or vice versa",
                                   "identifying limiting reagents",
                                   "calculating percent yield",
                                   "simulating ph changes in titrations",
                                   "tracking energy released",
                                   "tracking energy absorbed",
                                   "determining reaction rate based on time steps",
                                   "simulating half-life decay",
                                   "modeling temperature and pressure effects on volume",
                                   "assigning electron configurations",
                                   "sorting elements by some attribute (atomic radius, etc.)",
                                   "predicting solubility using polarity",
                                   "modeling phase transitions",
                                   "simulating catalyse effects based on yield",
                                   "estimating number of ions dissolved in solution"],
                      "q_types": ["estimating magnitude of change from initial conditions",
                                  "comparing theoretical predictions with observed outcomes",
                                  "modeling interaction strength between two entities",
                                  "estimating energy or resource consumption",
                                  "determining stability under varying conditions",
                                  "simulating feedback effects within a system",
                                  "computing probability of an event occurring",
                                  "balancing quantities between two or more systems",
                                  "tracking changes in a variable over discrete time steps",
                                  "converting between measurement units",
                                  "identifying a limiting factor in a process",
                                  "calculating efficiency or percent yield",
                                  "modeling growth or decay using exponential relationships",
                                  "predicting system behavior under changing conditions"],
                      "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra.",
                     },
    'adv-biology': {"subjects": ["molecular genetics and gene regulation",
                                 "epigenetics and chromatin remodeling",
                                 "advanced cell signaling pathways",
                                 "immunology and antigen-antibody interactions",
                                 "neurobiology and synaptic transmission",
                                 "developmental biology and morphogenesis",
                                 "biotechnology and genetic engineering",
                                 "systems biology and network analysis",
                                 "evolutionary genetics and population genomics",
                                 "metabolic pathways and regulation",
                                 "protein structure and enzyme kinetics",
                                 "advanced ecology and ecosystem dynamics",
                                 "cancer biology and cell cycle control",
                                 "stem cell biology and differentiation",
                                 "bioinformatics and computational biology"],
                    "concepts": ["identifying cell structures",
                                 "tracking growth stages",
                                 "classifying organisms",
                                 "analyzing genetic traits",
                                 "modeling photosynthesis process",
                                 "simulating respiration",
                                 "measuring enzyme activity",
                                 "monitoring population changes",
                                 "tracking nutrient cycles",
                                 "analyzing DNA sequences",
                                 "studying organism behavior",
                                 "classifying tissues",
                                 "measuring metabolic rates",
                                 "observing cell division",
                                 "mapping food chains",
                                 "analyzing habitats",
                                 "tracking environmental impacts",
                                 "monitoring immune responses",
                                 "studying reproduction methods",
                                 "measuring biodiversity"],
                    "q_types": ["identifying cell organelles",
                                "classifying species",
                                "predicting genetic inheritance",
                                "explaining metabolic pathways",
                                "calculating growth rates",
                                "determining enzyme effects",
                                "tracing nutrient flow",
                                "analyzing population trends",
                                "describing reproductive cycles",
                                "mapping food web interactions",
                                "interpreting DNA patterns",
                                "classifying tissue types",
                                "explaining respiration stages",
                                "predicting organism behavior",
                                "measuring biodiversity indices",
                                "describing immune system functions",
                                "analyzing environmental adaptations",
                                "identifying stages of mitosis",
                                "explaining photosynthesis steps",
                                "assessing habitat changes"],
                      "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra.",
                    },
    'adv-earth-science': {"subjects": ["geophysical fluid dynamics",
                                       "plate boundary dynamics and mantle convection",
                                       "advanced seismology and wave propagation",
                                       "isotope geochemistry and radiometric dating",
                                       "tectonophysics and crustal deformation modeling",
                                       "climate modeling and paleoclimate reconstruction",
                                       "geochemical cycles and elemental fluxes",
                                       "hydrogeology and groundwater flow modeling",
                                       "marine geophysics and ocean circulation",
                                       "volcanic eruption prediction and hazard assessment",
                                       "remote sensing and GIS applications",
                                       "cryosphere dynamics and ice sheet modeling",
                                       "natural disaster risk assessment and mitigation",
                                       "soil mechanics and geotechnical engineering",
                                       "earth system modeling and integration"],
                          "concepts": ["analyzing rock and soil composition",
                                       "tracking erosion or deposition over time",
                                       "modeling water cycle components",
                                       "simulating weather pattern changes",
                                       "measuring mineral hardness or density",
                                       "calculating sediment transport",
                                       "identifying landform types",
                                       "interpreting seismic wave data",
                                       "estimating age using radiometric dating",
                                       "mapping tectonic plate boundaries",
                                       "tracking changes in natural resource levels",
                                       "calculating energy flow in ecosystems",
                                       "classifying soil types",
                                       "measuring water quality parameters",
                                       "simulating volcanic activity",
                                       "modeling atmospheric pressure variations",
                                       "tracking glacier advance and retreat",
                                       "predicting flood likelihood",
                                       "calculating slope stability",
                                       "analyzing fossil distribution patterns"],
                          "q_types": ["tracking a gradual change in a physical property"
                                      "simulating an environmental process over several steps"
                                      "updating a value based on its interactions with its neighbors"
                                      "computing how a variable changes over time or space"
                                      "checking if conditions match a known pattern"
                                      "identifying significant points in a range"
                                      "flagging outliers or abnormal readings"],
                          "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra.",
                         },
    'adv-computer-science': {"subjects": ["advanced algorithm design and analysis",
                                          "divide and conquer algorithms",
                                          "dynamic programming techniques",
                                          "greedy algorithms and optimization",
                                          "graph algorithms (shortest path, spanning tree)",
                                          "network flow and matching algorithms",
                                          "computational geometry basics",
                                          "NP-completeness and intractability",
                                          "approximation algorithms",
                                          "randomized algorithms",
                                          "advanced data structures",
                                          "balanced binary search trees (AVL, Red-Black)",
                                          "B-trees and database indexing",
                                          "heaps and priority queues",
                                          "trie and suffix tree applications",
                                          "disjoint set union (union-find)",
                                          "concurrent and parallel programming",
                                          "synchronization and deadlocks",
                                          "multithreading and multiprocessing",
                                          "distributed systems fundamentals",
                                          "consensus algorithms (e.g., Paxos, Raft)",
                                          "cloud computing architectures",
                                          "virtualization and containerization",
                                          "operating system kernel design",
                                          "memory management and paging",
                                          "compiler design fundamentals",
                                          "lexical analysis and parsing",
                                          "code optimization techniques",
                                          "formal languages and automata theory",
                                          "regular expressions and finite automata",
                                          "context-free grammars and parsing",
                                          "Turing machines and decidability",
                                          "cryptography and secure communication",
                                          "public key infrastructure and RSA",
                                          "hashing and digital signatures",
                                          "network security protocols",
                                          "machine learning algorithms",
                                          "supervised and unsupervised learning",
                                          "neural networks and deep learning basics",
                                          "reinforcement learning concepts",
                                          "computer vision fundamentals",
                                          "natural language processing basics",
                                          "database transaction management",
                                          "concurrency control in databases",
                                          "data warehousing and OLAP",
                                          "big data frameworks (Hadoop, Spark)",
                                          "graph databases and NoSQL systems",
                                          "advanced web development concepts",
                                          "REST and GraphQL APIs",
                                          "web security and authentication",
                                          "blockchain and distributed ledger technology",
                                          "data structures",
                                          "sorting data",
                                          "searching through data",
                                          "string manipulation",
                                          "recursion",
                                          "basic algorithms",
                                          "memory simulation",
                                          "bitwise operations",
                                          "encoding",
                                          "decoding",
                                          "simulation of logic gates",
                                          "heaps",
                                          "hashing",
                                          "collisions",
                                          "finite state machines",
                                          "basic compilers",
                                          "basic interpreters",
                                          "virtual machines (simplified)",
                                          "cpu scheduling",
                                          "stack simulation",
                                          "queue simulation",
                                          "instruction sets",
                                          "memory layout",
                                          "rest api design basics",
                                          "request handling and routing",
                                          "json data parsing",
                                          "user authentication logic",
                                          "session/token simulation",
                                          "form submission processing",
                                          "crud operations (create, read, update, delete)",
                                          "input validation and sanitization",
                                          "pagination and search filtering",
                                          "error logging and handling",
                                          "configuration loading (e.g. from json and env dicts)",
                                          "rate limiting simulation",
                                          "basic job queue simulation",
                                          "email/message formatting",
                                          "file upload simulation",
                                          "time-based job simulation (e.g. cron-like behavior)",
                                          "simple database query emulation (no sql)",
                                          "microservice communication (mocked with dicts/function)",
                                          "simulated cloud storage or blob access",
                                          "basic analytics pipeline (e.g. log -> stats)",
                                          "api design",
                                          "frontend-backend communication",
                                          "database querying",
                                          "data serialization",
                                          "devops and deployment",
                                          "networking",
                                          "rate limiting",
                                          "code linting and formatting",
                                          "cloud storage interactions",
                                          "package management"],
                             "concepts": ["simulating execution over multiple steps",
                                          "updating states",
                                          "tracking resource usage over time",
                                          "checking consistency of a system",
                                          "validating a system",
                                          "counting the number of operations of a system",
                                          "comparing two outputs for correctness",
                                          "evaluating logic conditions",
                                          "classifying inputs",
                                          "checking if a pattern exists in another",
                                          "finding the most used memory/register/element",
                                          "summarizing the final state of a system",
                                          "tracking growth of a structure",
                                          "measuring depth, size, or height of a system",
                                          "flagging special or end cases",
                                          "computing differences between two configurations",
                                          "identifying when a system reaches a halting condition",
                                          "determining whether a structure satisfies constraints",
                                          "extracing fields from json/dictionaries",
                                          "transforming or formatting structured data",
                                          "merging or splitting structured inputs",
                                          "handling missing or malformed data",
                                          "simulating login/logout flow",
                                          "checking if session/token is vlid",
                                          "validating user inputs against criteria (without using input())",
                                          "counting user interactions",
                                          "returning appropriate http-like codes based on input",
                                          "simulating an api request and response cycle",
                                          "checking if input follows schema (without using input())",
                                          "verifying if request contains required fields",
                                          "simulating api unit test behavior",
                                          "resolving data conflicts"],
                             "q_types": ["formatting structured data",
                                         "identifying missing fields",
                                         "simulating an api response",
                                         "filtering logs or entries",
                                         "retrying failed operations",
                                         "handling state transitions",
                                         "processing a batch of inputs (without input())",
                                         "simulating a cache hit or miss",
                                         "validating constraints",
                                         "checking configuration values",
                                         "parsing a data structure",
                                         "generating example output",
                                         "detecting common user errors",
                                         "simulating user authentication flow",
                                         "tracking session validity",
                                         "counting occurrences in data",
                                         "handling error codes and messages",
                                         "simulating database query results",
                                         "validating json schema structure",
                                         "logging system events"],
                             "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra.",
                            },
    'adv-math': {"subjects": ["advanced algebraic manipulation",
                              "polynomials and factoring",
                              "quadratic equations",
                              "logarithms and exponentials",
                              "complex numbers",
                              "matrices and determinants",
                              "vector operations",
                              "linear transformations",
                              "systems of equations",
                              "conic sections",
                              "sequences and series",
                              "binomial theorem",
                              "probability distributions",
                              "conditional probability",
                              "combinatorics",
                              "trigonometric identities",
                              "unit circle applications",
                              "law of sines and cosines",
                              "inverse trigonometric functions",
                              "limits and continuity",
                              "derivatives and differentiation",
                              "applications of derivatives",
                              "integration techniques",
                              "definite and indefinite integrals",
                              "applications of integrals",
                              "differential equations basics",
                              "parametric equations",
                              "polar coordinates",
                              "infinite series and convergence",
                              "partial fractions",
                              "multivariable functions",
                              "partial derivatives",
                              "multiple integrals",
                              "vector calculus",
                              "linear algebra applications",
                              "eigenvalues and eigenvectors",
                              "probability theory",
                              "expected value and variance",
                              "random variables",
                              "statistics and hypothesis testing",
                              "graph theory basics",
                              "number theory fundamentals",
                              "modular arithmetic advanced",
                              "discrete mathematics",
                              "logic and proof techniques",
                              "set theory advanced",
                              "game theory basics",
                              "topology introduction"],
                 "concepts": ["performing basic arithmetic operations",
                              "applying order of operations",
                              "converting between fractions and decimals",
                              "calculating percentages",
                              "comparing ratios or proportions",
                              "working with negative numbers",
                              "finding factors of a number",
                              "identifying prime numbers",
                              "computing greatest common divisor",
                              "computing least common multiple",
                              "evaluating simple exponents",
                              "calculating square roots",
                              "solving simple linear equations",
                              "graphing points on a coordinate plane",
                              "determining the slope of a line",
                              "finding the perimeter of basic shapes",
                              "calculating the area of simple shapes",
                              "computing the volume of solids",
                              "measuring angles",
                              "classifying triangles by sides and angles",
                              "calculating circumference of a circle",
                              "determining probability of simple events",
                              "counting possible outcomes",
                              "finding mean, median, and mode",
                              "interpreting data from charts or tables",
                              "recognizing number patterns",
                              "continuing arithmetic sequences",
                              "solving systems of equations",
                              "applying calculus derivatives and integrals",
                              "analyzing limits and continuity",
                              "working with complex numbers",
                              "performing matrix operations",
                              "calculating eigenvalues and eigenvectors",
                              "solving differential equations",
                              "applying probability distributions",
                              "analyzing statistical data",
                              "performing vector calculations",
                              "working with sequences and series",
                              "using combinatorial methods",
                              "applying number theory concepts",
                              "performing transformations in coordinate geometry",
                              "working with multivariable functions",
                              "solving optimization problems",
                              "applying linear algebra techniques",
                              "analyzing convergence of series",
                              "computing Fourier transforms",
                              "solving non-linear equations"],
                 "q_types": ["solving for unknown values",
                             "simplifying complex expressions",
                             "expanding or factoring equations",
                             "analyzing polynomial roots",
                             "solving systems of equations",
                             "finding domain and range",
                             "evaluating limits",
                             "differentiating functions",
                             "finding slope or rate of change",
                             "optimizing with derivatives",
                             "calculating area under a curve",
                             "estimating with numerical integration",
                             "solving differential equations",
                             "modeling exponential growth or decay",
                             "applying trigonometric identities",
                             "proving trigonometric relationships",
                             "solving triangles with sines and cosines",
                             "analyzing periodic behavior",
                             "computing probabilities of events",
                             "analyzing probability distributions",
                             "finding expected values",
                             "calculating variance and standard deviation",
                             "performing hypothesis tests",
                             "analyzing sequences and series",
                             "determining convergence or divergence",
                             "applying binomial expansions",
                             "working with complex numbers",
                             "finding eigenvalues and eigenvectors",
                             "performing matrix operations",
                             "analyzing vector magnitudes and directions",
                             "computing cross and dot products",
                             "using polar or parametric equations",
                             "interpreting multivariable functions",
                             "computing gradients or partial derivatives",
                             "calculating surface or volume integrals",
                             "applying discrete counting principles",
                             "constructing mathematical proofs",
                             "applying modular arithmetic",
                             "analyzing graph properties",
                             "determining shortest paths or connections",
                             "modeling decision-making with game theory",
                             "analyzing logical statements",
                             "working with advanced set operations",
                             "describing continuous transformations",
                             "examining topological properties",
                             "checking numerical conditions",
                             "counting values with a property",
                             "tracking running totals or sequences",
                             "computing a transformation",
                             "detecting a classification",
                             "generating structured input",
                             "looping through a mathematical range",
                             "pattern detection or repetition",
                             "building up from a recurrence",
                             "checking equivalence across representations",
                             "grouping or filtering by criteria"],
                             
                 "notes": "You can use more complicated math for these problems, like calculus, geometry, and linear algebra.",
                },
}

general_attributes = {
    'general_concepts': ["reversing values",
                         "counting specific elements",
                         "checking conditions",
                         "removing duplicates",
                         "flattening nested structures",
                         "finding max or min values",
                         "searching for a target",
                         "grouping items",
                         "accumulating sums or products",
                         "comparing values",
                         "converting between types",
                         "validating input formats",
                         "extracting patterns of substrings",
                         "sorting data",
                         "working with indices or positions",
                         "sorting entities by a given attribute",
                         "classifying an outcome based on defined rules",
                         "tracking cumulative effects over multiple steps",
                         "assigning components to categories based on properties",
                         ],

    'general_q_types': ["checking conditions on each element",
                       "filtering a collection based on rules",
                       "transforming each element in a collection",
                       "accumulating a result cross a loop",
                       "validating properties of an input",
                       "reordering or sorting values",
                       "reformatting a string or number",
                       "traversing nested structures",
                       "searching for a target match",
                       "extracting or slicing part of a value",
                       "converting between representations",
                       "removing or replacing parts of data",
                       "tracking a running total or count",
                       "checking for uniqueness or duplicates",
                       "counting specific patterns or types",
                       "computing a simple numeric property"],
}