# Generated by Django 5.1.5 on 2025-04-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edtech_project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("determine_output", "Determine output"),
                    ("fill_in_vars", "Rename functions"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
