# Generated by Django 5.1.5 on 2025-07-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edtech_project", "0002_userhistory_problem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("determine_output", "Determine output"),
                    ("fill_in_vars", "Rename functions"),
                    ("drag_and_drop", "Drag and drop"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
