# Generated by Django 5.1.5 on 2025-07-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edtech_project", "0003_alter_userhistory_problem_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="problem_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
    ]
