# Generated by Django 5.1.5 on 2025-07-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edtech_project", "0004_userhistory_problem_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="userhistory",
            name="correct_code",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
