# Generated by Django 5.1.5 on 2025-07-06 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("edtech_project", "0005_userhistory_correct_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userhistory",
            old_name="correct_code",
            new_name="correct_answer",
        ),
    ]
