# Generated by Django 5.1.5 on 2025-07-12 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edtech_project", "0006_rename_correct_code_userhistory_correct_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userhistory",
            name="problem_type",
            field=models.CharField(
                choices=[
                    ("determine_output", "Determine output"),
                    ("fill_in_vars", "Write docstrings"),
                    ("drag_and_drop", "Drag and drop"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
